.\" 3.2
.SH FILES
LISTDIR/*.list
.br
DBDIR/*.data
.br
DBDIR/*.names
.br
DBDIR/*.index
.br
DBDIR/*.key
.br
DBDIR/*.titles
.SH SEE ALSO
.BR list (1),
.BR title (1),
.BR listall (1),
.BR lguide (1),
.BR ltrace (1),
.BR lindex (1),
.BR alist (1), 
.BR mkballot (1),
.BR lformat (1)
and
.BR lseen (1).
.SH BUGS
They are features!
.SH AUTHORS
.SS PROGRAMMERS
.PP
Colin Needham                           <col@imdb.com>
.rj 1
.B most of the programming
.PP
Philippe Queinnec                       <queinnec@dgac.fr>
.rj 1
.B Makefiles
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 1
.B some usage-logging code
.PP
Timo Lamminjoki                 <lamminjo@pcu.helsinki.fi>
.rj 1
.B compressed database support
.PP
Mark Harding                            <ccsmh@bath.ac.uk>
.rj 1
.B text justification routines
.SS LIST MAINTAINERS
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 2
.B Genres
.B Quotes
.PP
Andre Bernhardt                 <ujad@rz.uni-karlsruhe.de>
.rj 1
.B Producers
.PP
Murray Chapman                        <muzzle@cs.uq.oz.au>
.rj 1
.B Trivia
.PP
Michel Hafner                        <hafner@ifi.unizh.ch>
.rj 5
.B Alternative Names
.B Alternative Titles
.B Cinematographers
.B Composers
.B Movies
.PP
Mark Harding                            <ccsmh@bath.ac.uk>
.rj 8
.B Biographies
.B Certificates
.B Color Information
.B Countries
.B Crazy Credits
.B Release Dates
.B Running Times
.B Sound Mix
.PP
Robert Hartill                         <movie@cm.cf.ac.uk>
.rj 3
.B Locations
.B Production Companies
.B Tag Lines
.PP
Ron Higgins                     <rhiggins@carroll1.cc.edu>
.rj 1
.B Soundtracks
.PP
Harald Mayr                       <marvin@bike.augusta.de>
.rj 3
.B Costume Designers
.B Editors
.B Production Designers
.PP
Col Needham                             <col@imdb.com>
.rj 8
.B Actors
.B Actresses
.B Cast Completion
.B Directors
.B Goofs
.B Misc. Filmography
.B Movie Links
.B Ratings
.PP
Joachim Polzer                 <polzer@zedat.fu-berlin.de>
.rj 2
.B Literature
.B Technical Info
.PP
Jon Reeves                            <reeves@zk3.dec.com>
.rj 1
.B Writers
.PP
Colin Tinto                          <colint@spider.co.uk>
.rj 1
.B Plot Summaries
.SS CONTRIBUTORS
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 1
.B UNIX manpages
.PP
Teemu Antti-Poika                <anttipoi@cc.helsinki.fi>
.rj 1
.B LaTeX documentation
.PP
Robert Hartill                         <movie@cm.cf.ac.uk>
.rj 1
.B the script lfetch is based on
.PP
Philippe Queinnec                   <queinnec@enseeiht.fr>
.rj 1
.B imoviedb package (distributed separately)
.PP
 ...and last but not least all of you who send us information either directly
or via the email-server at movie@ibmpcug.co.uk.  Use "Subject: HELP ADD FULL" 
for information about how to use it.
.\"
.\"  /*******************************************************************\
.\"   * Copyright (C) 1995 Lars J Aas <larsa@colargol.stud.idb.hist.no> *
.\"   * based on documentation by C J Needham <col@imdb.com> 1995,      *
.\"   * permission is granted by the authors to freely distribute       *
.\"   *                        providing no fee of any kind is charged. *
.\"  \*******************************************************************/
.\"
