#!/bin/sh
#############################################################################
#
#  Script that creates postscript files of the manualpages.
#

if groff -Tps -man $1 > `basename $1 .1`.ps; then
  echo -n "";
else
  echo "Don't know how to produce postscript-files on this system.";
fi
