#!/bin/sh
#############################################################################
#
#  Script that creates preformatted manualpages.
#

if groff -Tascii -man $1 > `basename $1 .1`.cat; then
  echo -n "";
else
  echo "Don't know how to format your manpages on this system.";
fi
