.\" 3.2
.\"  /*******************************************************************\
.\"   * Copyright (C) 1995 Lars J Aas <larsa@colargol.stud.idb.hist.no> *
.\"   * based on documentation by C J Needham <col@imdb.com> 1995,      *
.\"   * permission is granted by the authors to freely distribute       *
.\"   *                        providing no fee of any kind is charged. *
.\"  \*******************************************************************/
.\"
.TH LSEEN 1 "10th August 1995" " " "The Internet Movie Database v3.2d"
.SH NAME
lseen \- for use in conjunction with movie ratings report voting support scripts.
.SH SYNOPSYS
lseen
.SH DESCRIPTION
This script is for use in conjunction with my
movie ratings report voting support scripts.
This program counts/sorts/formats lists, extracting films you have
seen based on data from your votelog file.
.PP
If you don't use voting support scripts, they are available via
anonymous ftp from cathouse.org in the directory /pub/cathouse/movies/database/tools/voting_scripts.Z.
.PP
If you'd like a copy of your votelog file from the movie ratings
database, contact cn@ibmpcug.co.uk via email, and he'll send it
to you.
.SH OPTIONS
There are
.BR database-options ,
.B output-options
and
.BR control-options .
.SS DATABASE-OPTIONS
.TP
.B \-acr
Use actors database.
.TP
.B \-acs
Use actresses database.
.TP
.B \-dir
Use directors database.
.TP
.B \-write
Use writers database.
.TP
.B \-comp
Use composers database.
.TP
.B \-cine
Use cinematographers database.
.TP
.B \-edit
Use editors database.
.TP
.B \-prodes
Use production-designers database.
.TP
.B \-costdes
Use costume-designers database.
.TP
.B \-prdcr
Use producers database.
.TP
.B \-misc
Use miscellaneous database.
.SS OUTPUT-OPTIONS
.TP
.B \-us
unsorted; don't sort data by total movies you have seen.
.TP
.B \-yr
Add the year of release to each title, and sort chronologically.
.TP
.B \-yru
Add the year of release, but leave unsorted.
.TP
.B \-mrr
Add movie ratings report info.
.TP
.B \-smrr
Add movie ratings report, sorted by average ratings.
.TP
.B \-vmrr
Add movie ratings report, sorted by number of votes.
.SS CONTROL-OPTIONS
.TP
.B \-min <val>
Limit output to people you've seen at least
.BR <val> of their movies.
.SH EXAMPLES
.TP
Count directors:
.B
lseen \-dir
.TP
Count actors and display ratings report and year of release info for
each movie:
.B
lseen \-acr \-mrr \-yr
.\" 3.2
.SH FILES
*.list
.br
/home/cn/listdb/versions/v3.3a/moviedb-3.3/dbs/*.data
.br
/home/cn/listdb/versions/v3.3a/moviedb-3.3/dbs/*.names
.br
/home/cn/listdb/versions/v3.3a/moviedb-3.3/dbs/*.index
.br
/home/cn/listdb/versions/v3.3a/moviedb-3.3/dbs/*.key
.br
/home/cn/listdb/versions/v3.3a/moviedb-3.3/dbs/*.titles
.SH SEE ALSO
.BR list (1),
.BR title (1),
.BR listall (1),
.BR lguide (1),
.BR ltrace (1),
.BR lindex (1),
.BR alist (1), 
.BR mkballot (1),
.BR lformat (1)
and
.BR lseen (1).
.SH BUGS
They are features!
.SH AUTHORS
.SS PROGRAMMERS
.PP
Colin Needham                           <cn@ibmpcug.co.uk>
.rj 1
.B most of the programming
.PP
Philippe Queinnec                       <queinnec@dgac.fr>
.rj 1
.B Makefiles
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 1
.B some usage-logging code
.PP
Timo Lamminjoki                 <lamminjo@pcu.helsinki.fi>
.rj 1
.B compressed database support
.PP
Mark Harding                            <ccsmh@bath.ac.uk>
.rj 1
.B text justification routines
.SS LIST MAINTAINERS
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 2
.B Genres
.B Quotes
.PP
Andre Bernhardt                 <ujad@rz.uni-karlsruhe.de>
.rj 1
.B Producers
.PP
Murray Chapman                        <muzzle@cs.uq.oz.au>
.rj 1
.B Trivia
.PP
Michel Hafner                        <hafner@ifi.unizh.ch>
.rj 5
.B Alternative Names
.B Alternative Titles
.B Cinematographers
.B Composers
.B Movies
.PP
Mark Harding                            <ccsmh@bath.ac.uk>
.rj 8
.B Biographies
.B Certificates
.B Color Information
.B Countries
.B Crazy Credits
.B Release Dates
.B Running Times
.B Sound Mix
.PP
Robert Hartill                         <movie@cm.cf.ac.uk>
.rj 3
.B Locations
.B Production Companies
.B Tag Lines
.PP
Ron Higgins                     <rhiggins@carroll1.cc.edu>
.rj 1
.B Soundtracks
.PP
Harald Mayr                       <marvin@bike.augusta.de>
.rj 3
.B Costume Designers
.B Editors
.B Production Designers
.PP
Col Needham                             <cn@ibmpcug.co.uk>
.rj 8
.B Actors
.B Actresses
.B Cast Completion
.B Directors
.B Goofs
.B Misc. Filmography
.B Movie Links
.B Ratings
.PP
Joachim Polzer                 <polzer@zedat.fu-berlin.de>
.rj 2
.B Literature
.B Technical Info
.PP
Jon Reeves                            <reeves@zk3.dec.com>
.rj 1
.B Writers
.PP
Colin Tinto                          <colint@spider.co.uk>
.rj 1
.B Plot Summaries
.SS CONTRIBUTORS
.PP
Lars J Aas               <larsa@colargol.stud.idb.hist.no>
.rj 1
.B UNIX manpages
.PP
Teemu Antti-Poika                <anttipoi@cc.helsinki.fi>
.rj 1
.B LaTeX documentation
.PP
Robert Hartill                         <movie@cm.cf.ac.uk>
.rj 1
.B the script lfetch is based on
.PP
Philippe Queinnec                   <queinnec@enseeiht.fr>
.rj 1
.B imoviedb package (distributed separately)
.PP
 ...and last but not least all of you who send us information either directly
or via the email-server at movie@ibmpcug.co.uk.  Use "Subject: HELP ADD FULL" 
for information about how to use it.
.\"
.\"  /*******************************************************************\
.\"   * Copyright (C) 1995 Lars J Aas <larsa@colargol.stud.idb.hist.no> *
.\"   * based on documentation by C J Needham <col@imdb.com> 1995,      *
.\"   * permission is granted by the authors to freely distribute       *
.\"   *                        providing no fee of any kind is charged. *
.\"  \*******************************************************************/
.\"
